SOLDIER_ROWS = 4
SOLDIER_COLS = 2
SOLDIER_BODY_ROWS = 3 # the upper part
SOLDIER_FEET_ROWS = 1 # the lower part



BOARD_ROWS = 25
BOARD_COLS = 50
CELL_SIZE = 20 # pixels per cell
CELL_PLAYER="p"
CELL_MINE="*"
CELL_FLAG="!"
CELL_EMPTY="-"


WINDOW_WIDTH = BOARD_COLS * CELL_SIZE
WINDOW_HEIGHT = BOARD_ROWS * CELL_SIZE

GRASS_SIZE= 2
FLAG_ROWS = 3
FLAG_COLS = 4

flag_row = BOARD_ROWS - FLAG_ROWS
flag_col = BOARD_COLS - FLAG_COLS

RUNNING_STATE=1
LOSS_STATE=0
WIN_STATE=2

GREEN = (0, 150, 0)

LOSE_FONT_SIZE = int(0.15 * WINDOW_WIDTH)

WIN_MESSAGE = "You Won!"
WIN_FONT_SIZE = LOSE_FONT_SIZE
WIN_COLOR = (89, 89, 89)
WIN_LOCATION = \
    (0.2 * WINDOW_WIDTH, WINDOW_HEIGHT / 2 - (WIN_FONT_SIZE / 2))

LOSE_MESSAGE = "You Lost!"
LOSE_COLOR = (0, 0, 0)
LOSE_LOCATION = \
    (0.2 * WINDOW_WIDTH, WINDOW_HEIGHT / 2 - (LOSE_FONT_SIZE / 2))



