SOLDIER_ROWS = 4
SOLDIER_COLS = 2
SOLDIER_BODY_ROWS = 3 # the upper part
SOLDIER_FEET_ROWS = 1 # the lower part

MINE_COLS = 3
MINE_ROWS = 1

BOARD_ROWS = 25
BOARD_COLS = 50
CELL_SIZE = 20 # pixels per cell
CELL_PLAYER="p"
CELL_MINE="*"
CELL_FLAG="!"
CELL_EMPTY="-"


WINDOW_WIDTH = BOARD_COLS * CELL_SIZE
WINDOW_HEIGHT = BOARD_ROWS * CELL_SIZE

GRASS_SIZE= 2
FLAG_ROWS = 3
FLAG_COLS = 4

flag_row = BOARD_ROWS - FLAG_ROWS
flag_col = BOARD_COLS - FLAG_COLS

RUNNING_STATE=1
LOSS_STATE=0
WIN_STATE=2



